package tracker.server;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_ADD_TASK,
    DELETE_TASK_BY_ID,
    DELETE_ALL_TASKS,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_ADD_SUBTASK,
    DELETE_SUBTASK_BY_ID,
    DELETE_ALL_SUBTASKS,
    GET_EPICS,
    GET_EPIC_BY_ID,
    POST_ADD_EPIC,
    DELETE_EPIC_BY_ID,
    DELETE_ALL_EPIC,
    GET_EPIC_SUBTASKS,
    POST_FILL_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED,
    UNKNOWN
}
